server:
  port: 8888
spring:
  activemq:
    broker-url: tcp:\\192.168.122.1:61616  #自己的mq服务地址
    user: admin
    password: admin
  jms:
    pub-sub-domain: false #队列
myqueue: boot_activeMQ_queue  #自定义队列名称
